### ISSUE TITLE
TypeError: Invalid value

### ISSUE THREAD

**Issue by michaelnisi** [michaelnisi/manger#15]
Curling for a specific episode, I passed an invalid since value:

```
curl -sS -d '[{"url": "http://feeds.podtrac.com/LhS5ax2CPGou", "since": "1488455988000"}]' localhost:8384/entries | json
```

Resulting in a crash:

```
09:57:56.785Z DEBUG manger: hit (url=http://feeds.podtrac.com/LhS5ax2CPGou, since=null, force=false, count=0)
    etag: FF5BECA3AF85D86B140EBA7E07F7F5E847308A86344075EF46BCC6A8AE4C130F
/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/index.js:19
  var codec = type.codec
                       ^

TypeError: Invalid value
    at util.assert (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/util.js:26:11)
    at Object.bytewise.encode (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/index.js:39:3)
    at Object.util.encodeList [as encode] (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/util.js:145:23)
    at serialize (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/index.js:23:22)
    at Object.bytewise.encode (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/index.js:60:18)
    at Object.util.encodeList [as encode] (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/util.js:145:23)
    at serialize (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/index.js:23:22)
    at Object.bytewise.encode (/Users/michaelnisi/workspace/manger-http/node_modules/bytewise-core/index.js:60:18)
    at encode (/Users/michaelnisi/workspace/manger-http/node_modules/manger/lib/schema.js:21:19)
    at entry (/Users/michaelnisi/workspace/manger-http/node_modules/manger/lib/schema.js:83:15)
```

Passing a Number, instead, works:

```
curl -sS -d '[{"url": "http://feeds.podtrac.com/LhS5ax2CPGou", "since": 1488455988000}]' localhost:8384/entries | json
```

**Comment by michaelnisi** [comment]
See #15
