### ISSUE TITLE
TypeError: Cannot set property 'url' of null

### ISSUE THREAD

**Issue by michaelnisi** [michaelnisi/manger#20]
Found another problematic feed, `http://www.designreviewpodcast.com/design-review.rss`:

```
16:27:34.065Z  INFO manger: request (method=GET)
    url: /entries/http%3A%2F%2Fwww.designreviewpodcast.com%2Fdesign-review.rss
/Users/michaelnisi/workspace/manger/index.js:554
    entry.url = uri
              ^

TypeError: Cannot set property 'url' of null
    at Pickup.onEntry (/Users/michaelnisi/workspace/manger/index.js:554:15)
    at emitOne (events.js:96:13)
    at Pickup.emit (events.js:188:7)
    at Pickup.entryclose (/Users/michaelnisi/workspace/manger/node_modules/pickup/index.js:159:10)
    at handle (/Users/michaelnisi/workspace/manger/node_modules/pickup/index.js:100:22)
    at Object.Pickup.parser.onclosetag (/Users/michaelnisi/workspace/manger/node_modules/pickup/index.js:125:5)
    at emit (/Users/michaelnisi/workspace/manger/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/michaelnisi/workspace/manger/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/michaelnisi/workspace/manger/node_modules/sax/lib/sax.js:889:7)
    at Object.write (/Users/michaelnisi/workspace/manger/node_modules/sax/lib/sax.js:1436:13)
```

The problem seems to be related to an unclosed item:

```
curl -sS http://www.designreviewpodcast.com/design-review.rss | grep 'Episode 9' -A15 -B3
```

**Comment by michaelnisi** [comment]
Fixed by **pickup** [08c7a70](https://github.com/michaelnisi/pickup/commit/08c7a70265b61c038f287e278c55f6a19f9e45ad)
