### ISSUE TITLE
Temporary redirect without URL

### ISSUE THREAD

**Issue by michaelnisi** [michaelnisi/manger#23]
Here’s, it seems, a temporary redirect failing during update.

```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: expected string: null
    at failureKey (/Users/michael/node/manger-http/node_modules/manger/index.js:226:3)
    at Feeds.MangerTransform.ignore (/Users/michael/node/manger-http/node_modules/manger/index.js:351:15)
    at Feeds.MangerTransform.request (/Users/michael/node/manger-http/node_modules/manger/index.js:367:12)
    at ClientRequest.onResponse (/Users/michael/node/manger-http/node_modules/manger/index.js:304:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
```

**Comment by michaelnisi** [comment]
Reviewing the code path along this strack trace offered no apparent reason for `url` being `null`. Investigate in which circumstances [message.url](https://nodejs.org/api/http.html#http_message_url) might become `null`.

**Comment by michaelnisi** [comment]
Maybe 835fbd3810c8598ceccab79f8455cc8d1a571243?

**Comment by michaelnisi** [comment]
This, of course, ends up as 'too many redirects' error, which is good enough.
